### ISSUE TITLE
bluetoothSerial is not defined

### ISSUE THREAD

**Issue by XiaoLiuAI** [don/BluetoothSerial#147]
Dear author.

I tried to use cordova:com.megster.cordova.bluetoothserial under Meteor. However, the inspector always says ```bluetoothSerial is not defined```. 
I am using 
 - meteor 1.1.0.2
 - cordova:com.megster.cordova.bluetoothserial  0.4.3

Could you please help me on this issue?

**Comment by don** [comment]
You're using meteor with Cordova on iOS or Android?

The global `bluetoothSerial` variable is created when Cordova (or PhoneGap) installs the plugin into your project.

**Comment by XiaoLiuAI** [comment]
I tried it on the iphone browser on my macbook pro. I followed the guide of Meteor on https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration.

It seems work with the ios simulator, so I misunderstand the way to use cordova (but the geolocation works on both browser and simulator). Do you know how to get the bluetooth data from web browser?

**Comment by don** [comment]
The BluetoothSerial plugin requires iOS (or Android) in order to run. It won't work in the simulator because the simulator does not support Bluetooth. It will not run in the desktop or phone browser.

Generally you're going to need an app for Bluetooth on the phone or desktop. The browser won't have access. There are some Chrome APIs for Bluetooth https://developer.chrome.com/apps/bluetooth but I haven't used them yet.

**Comment by XiaoLiuAI** [comment]
Thank you for your help!
