### ISSUE TITLE
Write not working

### ISSUE THREAD

**Issue by sonukapoor** [don/BluetoothSerial#150]
Hi Don, 

I am trying to write the below data through my android device on the TSL device and I receive a success. However when I do a read again, then I do not see the data updated. 

$scope.write = function() {
    var data = ".wr –db usr –da 1111222233334444 –dl 04 –do 0005 –ql all –qs s1 –qt b –sa 4 –sb epc –sd 0123456789abba9876543210 –sl 60 –so 0020 –st s1";
    $cordovaBluetoothSerial.write(data).then(function(){
      $scope.info = 'write success';
    }, function(error) {
      $scope.error = error;
    });
   };

Any ideas?

**Comment by don** [comment]
@sonukapoor I think this is a device specific communication problem rather than a plugin problem. See if you can find some sample code that works with you device and use that to understand how the communication should work. You could also try stack overflow, asking questions about bluetooth communication and that TSL device.
