### ISSUE TITLE
subscribe

### ISSUE THREAD

**Issue by biy-gxnn** [don/BluetoothSerial#260]
Hi,

I able to connect both android device1 to android device2.
In android device1 i try bluetoothserial.write("hello world").
How can my android device2 receive this "hello world" message?
Please help.

I uesd the funtion but the data is null or undefine,how to solve?
bluetoothSerial.subscribe('\n', function (data) {});

**Comment by don** [comment]
The Bluetooth Serial plugin does not support Android to Android communication because the plugin doesn't create a RFCOMM socket. This is completely possible on Android, I just haven't needed the functionality, so I haven't added it. Most of the code for creating a Bluetooth socket is in the project, it just needs be update for generic RFCOMM and have JavaScript APIs added. A few people have hacked forks to do this but no one has submitted a pull request. See https://github.com/don/BluetoothSerial/issues/50#issuecomment-66405396
