### ISSUE TITLE
How timeout Success or Failure callback if no data arrived from arduino device.

### ISSUE THREAD

**Issue by mumairofficial** [don/BluetoothSerial#279]
I am using JavaScript Promise pattern and no loops. How can I timeout in following situation:

If data not has arrived in `bluetoothSerial.subscribeRawData(success, failure);` success and failure callback.
Currently it is stuck in success or failure promise and user have no idea what is going on.

**Comment by don** [comment]
[bluetoothSerial.subscribeRawData](https://github.com/don/BluetoothSerial#subscriberawdata) registers a callback that is called when data arrives. The callback is the function passed as the success argument.

The success callback is called every time data arrives. This is why you can't use promises here. Promises can only be resolved one time. The success callback is called 0 to infinite times. If there are no notifications, it's never called. In other cases it's called over and over.

You could use an Observable in place of your Promise, but I recommend getting stuff working with plain old callbacks since it's easier to understand and debug.
