### ISSUE TITLE
question about subscribe function

### ISSUE THREAD

**Issue by paredesivan** [don/BluetoothSerial#291]
Don. I put in the code the "subscribe" function, and although the bluetooth device sends me data constantly, I receive only one message, terminated by the demiliter "/ n". I ask you. Is it a function that registers once and stops working when a message arrives or is it "open" to the constant listening of messages?

**Comment by don** [comment]
@paredesivan the success callback for subscribe is called every time the delimiter is seen in the incoming data.

See [this example](https://github.com/don/BluetoothSerial/tree/master/examples/Counter). [onMessage](https://github.com/don/BluetoothSerial/blob/master/examples/Counter/www/js/index.js#L21-L23) is called every time `\n` is in the data because of the call to [subscribe](https://github.com/don/BluetoothSerial/blob/master/examples/Counter/www/js/index.js#L14).

You can try [subscribeRawData](https://github.com/don/BluetoothSerial#subscriberawdata) to see all the incoming data and debug.
