### ISSUE TITLE
Get button signal from Bluetooth serial on Aurdino kit

### ISSUE THREAD

**Issue by yashinnhl** [don/BluetoothSerial#292]
Hi 
I am trying to get button signal (I push the button on Arduino) from Bluetooth serial on Arduino kit and alert it when happen. 
In other words, I have a button on Arduino when I push that, I want to send an alert or signal to my phone app. I used evothings Reading BLE app. I can easily turn on and off LED with the app. But I am trying to use a button to turn off the LED and send it to the app. 
Best

**Comment by don** [comment]
@yashinnhl Since the LED works, that means that Bluetooth is working. It sounds like you have and issue with your code. You could look at the [counter example](https://github.com/don/BluetoothSerial/tree/master/examples/Counter) which sends data from the Arduino to the phone. Your button press code should work similar. When the button is pressed, send a message to the phone. When the phone receives the data, do something.

If that doesn't fix the problem, post more details and sample code to the [EvoThings forum](https://evothings.com/forum/) or [Stack Overflow](http://stackoverflow.com).
