### ISSUE TITLE
Cannot Connect to Adafruit Trinket

### ISSUE THREAD

**Issue by smanda7** [don/BluetoothSerial#303]
I am trying to pair an Adafruit Trinket BLE board from an android phone app that I created in outsystems. I am using connectInsecure, and my app will pair my phone with an iPhone and my PC, but not able to connect to an Adafruit Trinket BLE board. When I connect it with an iPhone or PC, a box with a code shows up on my android and other device I want to pair to, and then my PC or iPhone has to either click pair or cancel. This might be the issue. Any way to solve this issue so I can connect to the Adafruit board and then read data? I am testing my app on a Samsung Galaxy S3.

**Comment by don** [comment]
Since you're using Bluetooth Low energy, you need to use a different plugin https://github.com/don/cordova-plugin-ble-central. This plugin uses Bluetooth Classic for Android.

There is an example project that works with the Bluetooth service on your Adafruit hardware. https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle
